### ISSUE TITLE
url to LinkedIn Profile as Additional Question

### ISSUE THREAD

**Issue by krcha** [GodsScion/Auto_job_applier_linkedIn#10]
It's absurd but I see a lot of companies asking for this as additional question:

<img width="740" alt="Screenshot 2024-08-21 at 19 08 51" src="https://github.com/user-attachments/assets/190b2f81-e1c3-4a9a-8c3b-c3f3e08afe58">

**Comment by GodsScion** [comment]
I know right! But, Added that question in the latest code, check it out!
