### ISSUE TITLE
Acknoledge/Confirm button isnt working

### ISSUE THREAD

**Issue by bipindr123** [GodsScion/Auto_job_applier_linkedIn#3]
There's a button with the label Acknowledge/Confirm which needs to be checked after the gender questions

**Comment by GodsScion** [comment]
I'm aware of it, but just to be sure we're talking about the same bug, could you post the screenshot the application took for debugging. You'll find it in folder " logs/screenshots/..."

**Comment by GodsScion** [comment]
Newer version implements this, please check it out
