### ISSUE TITLE
Address details no option to add Zip code Country and State

### ISSUE THREAD

**Issue by krcha** [GodsScion/Auto_job_applier_linkedIn#8]
Hi, I noticed that address details variables are not present in the config file

![Screenshot 2024-07-31 at 14 03 49](https://github.com/user-attachments/assets/b9eec6e0-49ec-4d8a-9b30-474f25caf3ac)

**Comment by GodsScion** [comment]
Please check the latest code, it can now answer address questions, you should be able to configure it in config/personals.py
