### ISSUE TITLE
In Applier Main 'bool' object has no attribute 'clear'

### ISSUE THREAD

**Issue by rosignol08** [GodsScion/Auto_job_applier_linkedIn#9]
I setup well the code and it connect and launched linkedin but I receive this i don't know why because all the boolean variable are completed with true or false.

**Comment by GodsScion** [comment]
I'll need a bit more info to debug, check the config file for true or false inputs, if they are all correct or not, a vaild true or false in Python would be True or False

**Comment by rosignol08** [comment]
Alright I will check this once I can today thank for your response 🙌

**Comment by rosignol08** [comment]
I tried to debut the file to see where the error is and I saw this : >>>> Now searching for "ALTERNANCE - Développeur" <<<<


Setting search location as: "Paris, France"
In Applier Main
'bool' object has no attribute 'clear'
2024-08-10 15:34:20.747172 i don't understant why they talk about boolean here because this part of the code is complete and the bool right after this step is not 'clear' search_location = "Paris, France"               # Some valid examples: "", "United States", "India", "Chicago, Illinois, United States", "90001, Los Angeles, California, United States", "Bengaluru, Karnataka, India", etc.


# >>>>>>>>>>> Job Search Filters <<<<<<<<<<<
''' 
You could set your preferences or leave them as empty to not select options except for 'True or False' options. Below are some valid examples for leaving them empty:

question_1 = ""                    # answer1, answer2, answer3, etc.
question_2 = []                    # (multiple select)
question_3 = []                    # (dynamic multiple select)

'''

sort_by = "Most recent"                       # "Most recent", "Most relevant" or ("" to not select) 
date_posted = "Past month"         # "Any time", "Past month", "Past week", "Past 24 hours" or ("" to not select)
salary = ""                        # "$40,000+", "$60,000+", "$80,000+", "$100,000+", "$120,000+", "$140,000+", "$160,000+", "$180,000+", "$200,000+"

easy_apply_only = True             # True or False

experience_level = ["Internship","Entry level"]

**Comment by Fairebol** [comment]
did you solve the bug? i have the same issue

**Comment by GodsScion** [comment]
The problem might have occurred when it was filling out search location field, I updated the code, this bug should not be a problem.
